### ISSUE TITLE
page numbering

### ISSUE THREAD

**Issue by jasminwu** [simurgh9/hw#1]
Hi, when the hw document is more than a page long, the page numbers change locations and appear on the top right instead. I was going to fork the .cls and .sty files to try and change this, but am unsure how to.

**Comment by simurgh9** [comment]
That is the default behaviour of the [AMS Article class](https://www.ctan.org/pkg/amsart). It is not something that is being done in the homework class provided in this package. E. g., try this document,

```latex
\documentclass[oneside]{amsart}
\author{Musa Al`Khwarizmi}
\date{\today}
\title{Minimal Complete Document}
\address{Bayt El-Hikmah}

\usepackage{lipsum}

% \usepackage{fancyhdr}
% \pagestyle{fancy}
% \cfoot{\thepage}

\begin{document} \maketitle
\lipsum[1-20]
\end{document}
```

You'll get the same behaviour of the page number being at the bottom for the front matter and then on the top right.

If you want to keep the page numbers at the bottom, a quick fix is using [fancyhdr](https://ctan.org/pkg/fancyhdr) package. Simply uncomment the commented part of the above code listing. You may also insert the commented section into a document using the homework class for the same desired effect. Do note that it changes the headers a bit. Read more [here](https://tex.stackexchange.com/a/557908/215221) and [here](https://tex.stackexchange.com/a/8847/215221).

**Comment by jasminwu** [comment]
Cheers, much appreciated
